user/website/views.py
from operator import truediv
from . import db,mail
from .models import bookingdb
from .models import User
from .models import galleryImageUpload
from flask import Blueprint, render_template, request,redirect, flash,url_for
from sqlalchemy import create_engine
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from flask_login import login_user,login_required, logout_user, current_user
import base64
from flask_mail import Mail,Message
from sre_constants import SUCCESS


views = Blueprint('views', __name__)
 
#login


class RegisterForm(FlaskForm):
    username=StringField(validators=[InputRequired(),Length(min=4,max=20)],render_kw={"placeholder":"username"})
    password=PasswordField(validators=[InputRequired(),Length(min=4,max=20)],render_kw={"placeholder":"password"})
    submit=SubmitField("Register")

    def validate_username(self, username):
        existing_user_username=User.query.filter_by(
            username=username.data).first()
        if existing_user_username:
            raise ValidationError("That username already exists.please choose different one.")

class LoginForm(FlaskForm):
    username=StringField(validators=[InputRequired(),Length(min=4,max=20)],render_kw={"placeholder":"username"})
    password=PasswordField(validators=[InputRequired(),Length(min=4,max=20)],render_kw={"placeholder":"password"})
    submit=SubmitField("Login")

@views.route("/")
def index():
    return render_template("home.html",user=current_user)


@views.route("/home")
def home():
    return render_template("home.html",user=current_user)

@views.route("/services")
def services():
    return render_template("services.html",user=current_user)



@views.route("/gallery")
def gallery():
    all_data=galleryImageUpload.query.all()
    return render_template("gallery.html",user=current_user,data=all_data)


@views.route("/login",methods=['get','post'])
def login():
    form= LoginForm()
    return render_template("login.html",form=form,user=current_user)

@views.route("/register",methods=['get','post'])
def register():
    form=RegisterForm()
    return render_template("register.html",form=form,user=current_user)

@views.route("/registerForm",methods=['get','post'])
def registerForm():
    if request.method=='POST':
        form=RegisterForm()
        if form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            print(user)
            if user:
                flash("Username alreay exists!! Try another name")
                return redirect(url_for('views.register',user=current_user))
            else:
                new_user=User(username=form.username.data, password=form.password.data, usertype="user")
                db.session.add(new_user)
                db.session.commit()
                user = User.query.filter_by(username=form.username.data).first()
                login_user(user,remember=True)
                return redirect(url_for('views.home',user=current_user))
        return render_template("register.html",form=form,user=current_user)


@views.route("/loginForm",methods=['get','post'])
def loginForm():
    if request.method=='POST':
        form=LoginForm()
        if form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            if user:
                if(user.password == form.password.data):
                    login_user(user,remember=True)
                    if(user.usertype == "user"):
                        return redirect(url_for('views.home',user=current_user))
                    else:
                        return redirect(url_for('views.galleryAdmin',user=current_user))
                else:
                    flash("invalid password")
                    return redirect(url_for('views.login',user=current_user))
            else:
                flash("username not found!!")
                return redirect(url_for('views.login',user=current_user))
        return render_template("register.html",form=form,user=current_user)

@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.login',user=current_user))

@views.route("/package")
def package():
    return render_template("package.html",user=current_user)

@views.route("/booking")
def booking():
    if current_user.is_authenticated:
        all_data=bookingdb.query.filter_by(username=current_user.username)
        print(current_user.username)
        return render_template("booking.html",user=current_user,data=all_data)
    else:
        return render_template("booking.html",user=current_user)


    

@views.route("/bookingForm",methods=['GET','POST'])
def bookingForm():
    if request.method == 'POST':
        if current_user.is_authenticated:
            name=request.form['name']
            email=request.form['email']
            address=request.form['address']
            package=request.form['package']
            date=request.form['date']
            phne=request.form['phne']
            username=current_user.username
            status="Pending"
            from datetime import datetime
            import datetime
            Db_date=bookingdb.query.filter_by(date=date,status="Accepted").first()
            t_date= datetime.date.today()
            cur=datetime.datetime.strptime(date,'%Y-%m-%d')
            c_date=cur.date()
            print(c_date)
            if(Db_date):
                flash("Date is already booked!!")
            elif(c_date<t_date):
                flash("Enter correct date")
            else:
                if(len(phne)!=10):
                    flash("Enter 10 digit of phone number!")
                    return redirect(url_for('views.booking',user=current_user))
                else:
                    if(phne.isdigit()==False):
                        flash("Only numbers are allowed!")
                        return redirect(url_for('views.booking',user=current_user))

                my_data=bookingdb(name,email,address,phne,package,date,username,status)
                db.session.add(my_data)
                db.session.commit()
                flash("Data send to admin...Wait for your response")
                email="keerthij.20cse@kongu.edu"
                subject="order received"
                msg="Hurray! , "+ my_data.name +" has order for date:"+my_data.date+" please respond to the customer!"
                message=Message(subject,sender="harinisham.20cse@kongu.edu",recipients=[email])
                message.body=msg
                mail.send(message)
                success ="message send"
                return redirect(url_for('views.booking',user=current_user,success=success))
        else:
            flash("please login to continuee.....!")
            return redirect(url_for('views.booking',user=current_user))

    return redirect(url_for('views.booking',user=current_user))


# admin

@views.route("/bookingAdmin")
def bookingAdmin():
    all_data=bookingdb.query.all()
    return render_template("bookingAdmin.html",data=all_data,user=current_user)


@views.route("/packageAdmin")
def packageAdmin():
    return render_template("packageAdmin.html",user=current_user)


@views.route("/galleryAdmin")
def galleryAdmin():
    all_data=galleryImageUpload.query.all()
    return render_template("galleryAdmin.html",data=all_data,user=current_user)

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg' ,'gif'])

def allowed_file(filename):
    return '.' in filename and filename.rsplit(".",1)[1].lower() in ALLOWED_EXTENSIONS

@views.route("/galleryImage",methods=['post'])
@login_required
def galleryImage():
    if request.method == 'POST':
        file = request.files['inputFile']

        if file.filename == '':
            flash("no image is selected")
            return redirect(url_for('views.galleryAdmin',user=current_user))
        
        if file and allowed_file(file.filename):
            name = file.filename
            data = file.read()
            final_pic=base64.b64encode(data).decode('ascii')
            upload = galleryImageUpload(name , final_pic)
            db.session.add(upload)
            db.session.commit()
            return redirect(url_for('views.galleryAdmin',user=current_user))
        else:
            flash("Only images are allowed")
            return redirect(url_for('views.galleryAdmin',user=current_user))
 
#accepting and rejecting orders

@views.route("/acceptConcept/<id>")
def acceptConcept(id):
    my_data=bookingdb.query.get(id)
    my_data.status="Accepted"
    db.session.commit()
    flash("Order has been accepted successfully!!")
    email=my_data.email
    subject="confiramtion mail"
    msg= my_data.name +" , Your booking for MakeupArt is confirmed :)"
    message=Message(subject,sender="harinisham.20cse@kongu.edu",recipients=[email])
    message.body=msg
    mail.send(message)
    success ="message send"
    return redirect(url_for('views.bookingAdmin',user=current_user,success=success))

@views.route("/rejectConcept/<id>")
def rejectConcept(id):
    my_data=bookingdb.query.get(id)
    my_data.status="Rejected"
    db.session.commit()
    flash("Order has been rejected successfully!!")
    email=my_data.email
    subject="Rejection mail"
    msg="Sorry, "+ my_data.name +"Your booking for MakeupArt is rejected :("
    message=Message(subject,sender="harinisham.20cse@kongu.edu",recipients=[email])
    message.body=msg
    mail.send(message)
    success ="message send"
    return redirect(url_for('views.bookingAdmin',user=current_user,success=success))

@views.route("/cancelConcept/<id>")
def cancelConcept(id):
    my_data=bookingdb.query.get(id)
    my_data.status="Canceled"
    db.session.commit()
    flash("Your order has been cancelled!!")
    email="keerthij.20cse@kongu.edu"
    subject="cancellation mail"
    msg="Sorry, "+ my_data.name +" has cancelled the booking for MakeupArt :("

user/website/templates/booking.html
{%extends "layout.html"%}
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-success alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">x</span>
      </button>
      {{message}}
    </div>
        
  {% endfor %}
{%endif %}
{% endwith %}


    <section class="sec">
      <h1 id="heading">Booking</h1>
      <div class="container">
        <div class="row">
          <div class="col-6">
            <img class="book-img" src="../static/images/finalimg.jpg" alt="" height="500px">
          </div>
          <!-- <div class="col">
            <p>I believe all women are pretty without makeup- but with the right makeup can be pretty powerful</p>
          </div> -->
          <div class="col-6">
            <!-- form starts -->
            <div class="formbox">
              <form class="row g-3" method="post" action="{{url_for('views.bookingForm')}}">
                  <div class="col-md-12">
                      <label for="inputEmail4" class="form-label" style="font-size:20px;color:brown;">Name</label>
                      <input type="text" class="form-control" name="name" required>
                  </div>
                  <div class="col-md-12">
                      <label for="inputEmail4" class="form-label" style="font-size:20px;color:brown;">Email</label>
                      <input type="email" class="form-control" name="email" required>
                  </div>
                  <div class="col-md-12">
                      <label for="inputAddress" class="form-label" style="font-size:20px;color:brown;">Address</label>
                      <input type="text" class="form-control" name="address" required>
                  </div>
                  <div class="col-md-12">
                      <label for="inputAddress" class="form-label" style="font-size:20px;color:brown;">Phone No</label>
                      <input type="tel" class="form-control" name="phne" required>
                  </div>
                  
                  <div>
                    <label for="package" style="font-size:20px;color:brown;">Choose a package:</label><br>
                    <select class="custom-select selmenu" id="package" name="package" style="height: 50%;" required> 
                      <option value="Bronze">Bronze</option>
                      <option value="Silver">Silver</option>
                      <option value="Gold">Gold</option>
                      <option value="Platinum">Platinum</option>
                    </select>
                  </div>


                  <div class="col-md-12">
                      <label for="inputAddress2" class="form-label" style="font-size:20px;color:brown;">Date</label>
                      <input type="date" class="form-control" id="inputDate" placeholder="dd/mm/yyyy" name="date" required>
                  </div>
                  
                  <div class="col-12">
                      <button type="submit" class="btn btn-primary" id="book" >BOOK</button>
                  </div>
                  
              </form>
            </div>
            <!-- form ends -->
          </div>
          
        </div>
      </div>
    
                    
     {% if user.is_authenticated %}
     <table class="table">
      <thead>
        <tr>
          <th scope="col">name</th>
          <th scope="col">email</th>
          <th scope="col">address</th>
          <th scope="col">phone</th>
          <th scope="col">package</th>
          <th scope="col">Date</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
          {% for row in data %}
              <tr>
                  <td>{{row.name}}</td>
                  <td>{{row.email}}</td>
                  <td>{{row.address}}</td>
                  <td>{{row.phne}}</td>
                  <td>{{row.package}}</td>
                  <td>{{row.date}}</td>
                  {% if row.status=="Accepted" %}
                    <td style="color:green ;">{{row.status}}</td>
                  {% elif row.status=="Pending"  %}
                    <td style="color:blue ;">{{row.status}}</td>
                  {% else %}
                    <td style="color:red ;">{{row.status}}</td>
                  {% endif %}
                  {% if row.status!="Rejected" and row.status!="Canceled" %}}
                    <td><form method="post" action="/cancelConcept/{{row.id}}"><a type="submit" class="btn-lg btn-danger" href="/cancelConcept/{{row.id}}"> cancel </a></form></td>
                  {% endif %}
              </tr>
          {% endfor %}
      </tbody>
    </table>
    {% endif %}
  
</section>
{%endblock%}

user/website/templates/bookingAdmin.html
{%extends "layoutAdmin.html"%}
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-success alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">x</span>
      </button>
      {{message}}
    </div>
        
  {% endfor %}
{%endif %}
{% endwith %}
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">s.no</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Address</th>
        <th scope="col">phone</th>
        <th scope="col">package</th>
        <th scope="col">Date</th>
        <th scope="col">Status</th>

      </tr>
    </thead>
    <tbody>
        {% for row in data %}
            <tr>
                <td>{{row.id}}</td>
                <td>{{row.name}}</td>
                <td>{{row.email}}</td>
                <td>{{row.address}}</td>
                <td>{{row.phne}}</td>
                <td>{{row.package}}</td>
                <td>{{row.date}}</td>
                {% if row.status == "Pending" %}
                  <td><form method="post" action="/acceptConcept/{{row.id}}"><a type="submit" class="btn-lg btn-success " href="/acceptConcept/{{row.id}}"> Accept </a></form></td>
                  <td><form method="post" action="/rejectConcept/{{row.id}}"><a type="submit" class="btn-lg btn-danger" href="/rejectConcept/{{row.id}}"> reject </a></form></td>
                {% else %}
                  {% if row.status=="Accepted" %}
                    <td style="color:green ;">{{row.status}}</td>
                    <td></td>
                  {% else %}
                    <td style="color:red ;">{{row.status}}</td>
                    <td></td>
                  {% endif %}
                {% endif %}
               
            </tr>
        {% endfor %}
    </tbody>
  </table>
{%endblock%}
    

   

user/website/templates/gallery.html
{%extends "layout.html"%}
{% block content %}
    <section class="gallery" id="gallery">
        <div class="gallery-content">
            <div class="section-title">
                <h1><i>gallery</i></h1>
                <div class="gallery-list-img">
                  {% for row in data %}
                     <div class="gallery-img">
                        <img src="data:;base64,{{ row.final_img }}" width="300px" height="300px">
                     </div>
                  {%endfor%}
            </div>
        </div>
    
    </section>
{%endblock%}

user/website/templates/galleryAdmin.html
{%extends "layoutAdmin.html"%}
{% block content %}

{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
          <span aria-hidden="true">x</span>
        </button>
        {{message}}
      </div>
          
    {% endfor %}
  {%endif %}
{% endwith %}

<h1 style="text-align: center; margin-top: 15px;"><i>GALLERY</i></h1>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">upload an image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form method="post" action="{{url_for('views.galleryImage')}}"  enctype="multipart/form-data">
              <div class="form-group">
                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="inputFile">
              </div>
              <button type="submit" class="btn btn-primary">Upload</button>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

<section class="gallery" id="gallery">
  <div class="gallery-content">
      <div class="section-title">
          
          <div class="gallery-list-img">
            {% for row in data %}
              <div class="gallery-img">
                <img src="data:;base64,{{ row.final_img }}" width="300px" height="300px">
              </div>
            {%endfor%}
      </div>
  </div>

</section>
 <!-- Button trigger modal -->
 <button type="button" class="btn-lg btn-primary plus_icon" data-toggle="modal" data-target="#exampleModal" >
  <i class="fa-solid fa-plus"></i> Add Image
</button>
	
{%endblock%}

user/website/templates/home.html
{%extends "layout.html"%}
{% block content %}
    
<!--Start Home Section-->
<section class="home">
    <div class="container">
        <div class="home-img">
            <img src="../static/images/home-img.png">
        </div>
        <div class="home-content">
            <h1>Your big day<br><span>in style</span></h1>
            <p>Come see our bride's corner and take the opportunity to schedule your date.</p>
        </div>
    </div>
    
{% endblock %}

user/website/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>HOME</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Nunito:ital,wght@0,200;1,500;1,700&display=swap" rel="stylesheet">

    <!-- navBar styles -->
    <link href="{{url_for('static',filename='css/booking.css')}}" rel="stylesheet">
    <link href="{{url_for('static',filename='css/gallery.css')}}" rel="stylesheet">
    <link href="{{url_for('static',filename='css/home.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/navBar.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/package.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/services.css')}}">

    <!-- font awsome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />


</head>

<body>
    <!--Navbar section-->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <div style="height:55px;width:55px;border-radius:50px;margin-top:-198%;margin-left:-100%;"><img src="https://p.kindpng.com/picc/s/554-5541199_hair-stylist-clipart-hair-stylists-png-transparent-png.png" style="width:100%;height:100%;">
                <h5 style="margin-left:201%;margin-top:-75%">Makeup-Art</h5>
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mr-auto">
                <li class="nav-item ">
                    <a class="nav-link active" href="{{url_for('views.home')}}">HOME </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('views.services')}}">SERVICES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('views.package')}}">PACKAGE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('views.gallery')}}">GALLERY</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('views.booking')}}">BOOKING</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('views.logout')}}">logout</a>
                </li>
                {% else %}
                <li class="nav-item" >
                    <a class="nav-link" href="{{url_for('views.login')}}" class="login">
                LOGIN
              </a> {% endif %}
                </li>
            </ul>

        </div>
    </nav>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <div>
        {% block content%} {%endblock%}
    </div>
</body>

</html>

user/website/templates/layoutAdmin.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>HOME</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Nunito:ital,wght@0,200;1,500;1,700&display=swap" rel="stylesheet">

    <!-- navBar styles -->
    <link href="{{url_for('static',filename='css/booking.css')}}" rel="stylesheet">
    <link href="{{url_for('static',filename='css/gallery.css')}}" rel="stylesheet">
    <link href="{{url_for('static',filename='css/home.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/navBar.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/package.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/services.css')}}">

    <!-- font awsome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
</head>
  <body>
    <!--Navbar section-->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div style="height:55px;width:55px;border-radius:50px;margin-top:-10%;margin-left:-3%;"><img src="https://p.kindpng.com/picc/s/554-5541199_hair-stylist-clipart-hair-stylists-png-transparent-png.png" style="width:100%;height:100%;">
            <h5 style="margin-left:201%;margin-top:-75%">MakeupArt</h5>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.galleryAdmin')}}">Gallery</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.bookingAdmin')}}">Booking</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.logout')}}">logout</a>
            </li>
            {% else %}
            <li class="nav-item" style="margin-top:1%;">
              <a class="nav-link" href="{{url_for('views.login')}}" class="login">
                LOGIN
              </a>
            </li>
            {% endif %}
          </ul>

        </div>
      </nav>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <div>
        {% block content%}
        {%endblock%}
    </div>
  </body>
</html>

user/website/templates/login.html
{%extends "layout.html"%} {% block content %} {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
<div class="alert alert-success alert-dismissable" role="alert" style="height:100%;">
    <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">x</span>
            </button> {{message}}
</div>

{% endfor %} {%endif %} {% endwith %}

<div style="background:url('../static/images/login.jpg');padding-bottom:28%;background-repeat: no-repeat;background-size: cover;width: 100%;height: 760px;">
    <div class="all">
        <div class="head">
            Login
        </div>
        <form method="post" class="lform" action="{{url_for( 'views.loginForm')}}">
            {{ form.hidden_tag() }} {{ form.username (class_="username ")}} {{ form.password (class_="password ") }} {{ form.submit(class_="submit ") }}
        </form>
        <a href="{{url_for( 'views.register')}} " class="signup ">Create an new account? signup</a>
    </div>
</div>
{%endblock%}

user/website/templates/register.html
{%extends "layout.html"%} 
{% block content %} 
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">x</span>
                </button> {{message}}
            </div>
        {% endfor %}
    {%endif %}
{% endwith %}
<div style="background:url('../static/images/login.jpg');padding-bottom:28%;height:100%;width:100%;" class="body">
    <form method="post" action="{{url_for('views.registerForm')}}">
        <div class="formForm">
            <div class="head">
                Signup
            </div>
            <div>
                {{ form.hidden_tag() }}
            </div>
            <div>
                {{ form.username (class_="username ")}}
            </div>
            <div>
                {{ form.password (class_="password")}}
            </div>
            <div>
                {{ form.submit(class_="submit") }}
            </div>
        </div>
    </form>
    <a href="{{url_for('views.login')}}" class="signup">Already have an Account? login</a>
</div>
{%endblock%}